pipeline {
    
    agent none

    stages {
        
        stage("build"){
            agent {
                docker {
                    image 'python:2.7.16-slim'
                    args '--user root'
                }
            }
            when { 
                changeset "**/vote/**"
            }
            steps{
                echo "Building ..."
                dir("vote"){
                    sh "pip install -r requirements.txt"
                }
            }
        }
        
        stage("test"){
            agent {
                docker {
                    image 'python:2.7.16-slim'
                    args '--user root'
                }
            }
            when { 
                changeset "**/vote/**"  
            }
            steps{
                echo "Unit testing ..."
                dir("vote"){
                    sh "pip install -r requirements.txt"
                    sh "nosetests -v"
                }                
            }
        }
        stage("docker-package"){
            agent any
            when {
                branch "master"
                changeset "**/vote/**"
            }
            steps{
                echo "Packaging into docker container..."

                script {
                    docker.withRegistry("","dockerLogin"){
                        def workerImage = docker.build("grial1/vote:v${env.BUILD_ID}","./vote")
                        workerImage.push()
                        workerImage.push("${env.BRANCH_NAME}")
                    }
                }
            }
        }
    }
    post {
        always {
            echo "Build pipeline has finished!"
            slackSend (channel: "instavot-cd", message: "Build Started - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }

        failure {
            slackSend (channel: "instavot-cd", message: "Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
        
        success {
            slackSend (channel: "instavot-cd", message: "Build Succeeded - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
    }
}